language: node_js
node_js:
  - "7"

env:
  - SNYK_TOKEN="698bcdaf-92de-4a07-bdb7-df4a3fc358b3"

before_install:
  - npm i -g npm@5
  - npm i -g elm@0.18
  - npm i -g snyk

script:
  - npm run-script build
  - npm test