language: node_js
node_js:
  - "8"

env:
  - SNYK_TOKEN="698bcdaf-92de-4a07-bdb7-df4a3fc358b3"

before_install:
  - npm i -g npm@latest
  - npm i -g elm@latest
  - npm i -g snyk@latest
  - npm i -g elm-test@latest

install:
  - npm install --no-package-lock

script:
  - travis_retry travis_wait npm run-script build
  - travis_retry travis_wait npm test

deploy:
  provider: heroku
  api_key:
    secure: x334pwy5thxf2vVh3MEN3Rd15xCGawAY5WW1wIqhAI5trolxAYuYFrB/FUIpV6ERoYY+G9kyu/igEDc3lx9FisJo7oJmhGjZEHtA6INpXVJwlKy3d/snXGFQ955kTkBfDHHg1gZZgVYgBzNVh1UvV8Hr74hq7+zGvzPc4Z4Cr2u9VtdY7Kv1MBCTib5ZyGnyQMkdxlaq9IT5NGZask/wB+Wssh7o9oP3wE1kGiUAKGi8QhOhw6ymgKDZsMo4fCIvwNXFGZRqysy9mLD9YHMOa3I2pWCtPRC1tBrbbdkbW78tqvLTN0/u6AMnd+2DRZnad6+6zANevF5EQZ0vfB4hD9DBY/ItahvOMAJdmKJMMMdUCSkHmkxGoEVP94hK4OINNOejeq5luLSeNnBg8QmXoCaLhs0ad8J3Yt4BXM/3Z3/oGX41FUy9HaOcIJCgsfh9Cspil9Saa7Ir3tt49+PoLfZt1r2eBSGWwSrw/ai/xDWv/P6leeU/335CeyqJEJlX7RXYC04VyIN5JVV/nYPZN2DOe0Atv92nctBrLXDBcYO7G2+NykDmzv6oRZ5glwjSztJX4yMHENHNhHJzx4sHN4Hqw47jxWlaDhRga0mnsio9W4oqe9IOJOIPJH4/pEKs3lHCV7LXIOyObtPJ/Mcu5GL3bW1QZNCHe54NPVQpgdY=
  skip_cleanup: true