language: node_js
node_js:
  - "8"

env:
  - SNYK_TOKEN="698bcdaf-92de-4a07-bdb7-df4a3fc358b3"

before_install:
  - npm i -g npm@latest
  - npm i -g elm@latest
  - npm i -g snyk@latest
  - npm i -g elm-test@latest

install:
  - npm install --no-package-lock

script:
  - travis_retry npm run-script build
  - npm test