#!/usr/bin/env node
const TYPES = require("./ioc/types").default;
const container = require("./ioc/container").default();
const conf = require("config");

const app = container.get(TYPES.App);
app
  .init(container)
  .then(() =>
    setTimeout(
      () =>
        app.start(
          process.env.PORT || conf.get("env.port") || "3000",
          process.env.URL || conf.get("env.url") || "localhost",
        ),
      2000, // Waiting 2 secs to avoid compilation conflicts with hmr
    ),
  )
  .catch(err => {
    throw err;
  });
