#!/usr/bin/env node
const TYPES = require("./ioc/types").default;
const container = require("./ioc/container").default();
const conf = require("config");

const app = container.get(TYPES.App);
app.init(container);
app.start(
  process.env.PORT || conf.get("env.port") || "3000",
  process.env.URL || conf.get("env.url") || "localhost");
