# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
defaults: &defaults
  docker:
    - image: node:8.4
  working_directory: /workspace/elm-express-boilerplate

version: 2
jobs:
  clone:
      <<: *defaults
      steps:
        - checkout
        - persist_to_workspace:
            root: /workspace
            paths:
              - elm-express-boilerplate
  
  dependencies:
      <<: *defaults
      steps:
        - attach_workspace:
            at: /workspace
        - restore_cache:
            keys:
              - v7-bundle-{{ checksum "package.json" }}
        - restore_cache:
            keys:
              - v7-bundle-{{ checksum "elm-package.json" }}
        - run: npm install
        - run: npm run snyk:t
        - run: npm run build:elm
        - save_cache:
            key: v7-bundle-{{ checksum "package.json" }}
            paths:
              - node_modules
        - save_cache:
            key: v7-bundle-{{ checksum "elm-package.json" }}
            paths:
              - elm-stuff
        - persist_to_workspace:
            root: /workspace
            paths:
              - elm-express-boilerplate/node_modules
              - elm-express-boilerplate/elm-stuff

  build:
      <<: *defaults
      steps:
        - attach_workspace:
            at: /workspace
        - run: npm run build

  test:
      <<: *defaults
      steps:
        - attach_workspace:
            at: /workspace
        - run: cp -r elm-stuff tests
        - run: ls tests
        - run: npm test
        - run:
            command: npm test
            when: on_fail
            no_output_timeout: 20m
        - run: npm run snyk:m

  heroku_deploy:
      <<: *defaults
      steps:
        - attach_workspace:
            at: /workspace
        - run: bash .circleci/setup-heroku.bash
        - add_ssh_keys:
            fingerprints:
              - "7c:77:d2:07:31:3f:64:89:ff:77:cb:97:25:89:97:07"
        - deploy:
            name: Deploy master to Heroku
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git push heroku master
              fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - clone
      - dependencies:
          requires:
            - clone
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - heroku_deploy:
          requires:
            - build
            - test