# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  clone:
      docker:
        - image: node:8.4
      working_directory: /elm-express-boilerplate
      steps:
        - checkout
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - save_cache:
            key: v6-repo-{{ checksum ".circle-sha" }}
            paths:
              - /elm-express-boilerplate
  
  dependencies:
      docker:
        - image: node:8.4
      working_directory: /elm-express-boilerplate
      steps:
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - restore_cache:
            keys:
              - v6-repo-{{ checksum ".circle-sha" }}
        - restore_cache:
            keys:
              - v6-bundle-{{ checksum "package.json" }}
        - restore_cache:
            keys:
              - v6-bundle-{{ checksum "elm-package.json" }}
        - run: npm install
        - run: npm run snyk:t
        - run: npm run build:elm
        - save_cache:
            key: v6-bundle-{{ checksum "package.json" }}
            paths:
              - /elm-express-boilerplate/node-modules
        - save_cache:
            key: v6-bundle-{{ checksum "elm-package.json" }}
            paths:
              - /elm-express-boilerplate/elm-stuff

  build:
      docker:
        - image: node:8.4
      working_directory: /elm-express-boilerplate
      steps:
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - restore_cache:
            keys:
              - v6-repo-{{ checksum ".circle-sha" }}
        - restore_cache:
            keys:
              - v6-bundle-{{ checksum "package.json" }}
        - restore_cache:
            keys:
              - v6-bundle-{{ checksum "elm-package.json" }}
        - run: npm install
        - run: npm run build

  test:
      docker:
        - image: node:8.4
      working_directory: /elm-express-boilerplate
      steps:
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - restore_cache:
            keys:
              - v6-repo-{{ checksum ".circle-sha" }}
        - restore_cache:
            keys:
              - v6-bundle-{{ checksum "package.json" }}
        - restore_cache:
            keys:
              - v6-bundle-{{ checksum "elm-package.json" }}
        - run: npm install
        - run: cp -r elm-stuff tests
        - run: npm test
        - run: npm run snyk:m

  heroku_deploy:
      docker:
        - image: node:8.4
      working_directory: /elm-express-boilerplate
      steps:
        - run: bash .circleci/setup-heroku.bash
        - add_ssh_keys:
            fingerprints:
              - "7c:77:d2:07:31:3f:64:89:ff:77:cb:97:25:89:97:07"
        - deploy:
            name: Deploy master to Heroku
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git push heroku master
              fi

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - clone
      - dependencies:
          requires:
            - clone
      - build:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
      - heroku_deploy:
          requires:
            - build
            - test